version: "3.7"

services:
  nodejs:
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      PGHOST: postgres
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGPORT: 5432
    volumes:
      - ./nodejs:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"